### ISSUE TITLE
make font imports

### ISSUE THREAD

**Issue by Ilya-Dokuchaev** [Ilya-Dokuchaev/webpack-boilerplate#4]
---
name: Font asset loading 
about: Optimized font assets loading
---

**Is your feature request related to a problem? Please describe.**
It's similar as images are loaded in. So there's actually no problem at all

**Describe the solution you'd like**
Support for files with` ext : /\(eot|ttf|woff|woff2)$/ `that webpack will built as assets into ./dist folder and also be optimized
for building

**Comment by Ilya-Dokuchaev** [comment]
I want to make it work with all types of fonts

**Comment by itspunkaj** [comment]
can you explain it a bit more

**Comment by Ilya-Dokuchaev** [comment]
> can you explain it a bit more
I've done some description on issue.
A little bit of a context here. I'm actually know how to do it, so this is more like my wip sandbox study kind of a project to get more familiar with github processes and webpack at the same time. Actually never thought that someone will get here to close the issue. I think there is an option to make the repo private, but as far as I know the gh-pages would not work with the private repo
